export const ROUTES = {
  dashboard: '/',
  users: '/users',
  liveAccounts: '/live-accounts',
  recordings: '/recordings',
  supportTickets: '/support-tickets',
  jobs: '/jobs',
  billing: '/billing',
  subscriptions: '/subscriptions',
  deliveries: '/deliveries',
  telemetry: '/telemetry',
  trialConfig: '/trial-config',
  countryBlock: '/country-block',
  login: '/login',
};
